services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DJANGO_SUPERUSER_USERNAME}
      POSTGRES_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/ssl/private/postgresdb.key:/var/lib/postgresql/postgresdb.key
      - /etc/ssl/certs/postgresdb.crt:/var/lib/postgresql/postgresdb.crt
    command: >
      bash -c "if [ \"${DEBUG}\" = \"True\" ]; then
                docker-entrypoint.sh postgres -c ssl=off;
              else
                docker-entrypoint.sh postgres \
                -c ssl=on \
                -c ssl_cert_file=/var/lib/postgresql/postgresdb.crt \
                -c ssl_key_file=/var/lib/postgresql/postgresdb.key \
                -c ssl_passphrase_command='echo $SSL_PASSPHRASE';
              fi"
    networks:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    #ports: ["8000:8000"] # SECURITY WARNING: comment this line in production!
    develop: { watch: [ { action: sync, path: ./backend, target: /app, ignore: [venv/] } ] }
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend
      - frontend
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - frontend_dist:/app/dist
    #ports: ["5173:5173"] # SECURITY WARNING: comment this line in production!
    develop: { watch: [ { action: sync, path: ./frontend, target: /app, ignore: [node_modules/] } ] }
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - frontend
    restart: always
  
  memcached:
    image: memcached:1.6.34
    command: memcached -m 128 -p 11211 -u memcache
    networks:
      - backend
    restart: always

  nginx:
    image: nginx:1.27.3
    environment:
      ALLOWED_HOST: ${ALLOWED_HOST}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.tmp
      - frontend_dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    command: >
      bash -c "[ \"${DEBUG}\" = \"True\" ] && sleep infinity; envsubst '$$ALLOWED_HOST' < /etc/nginx/nginx.conf.tmp > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    networks:
      - frontend
      - backend
    restart: always

volumes:
  postgres_data:
    driver: local
  frontend_dist:
    driver: local

networks:
  backend:
  frontend:
