services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DJANGO_SUPERUSER_USERNAME}
      POSTGRES_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - frontend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
      - ./staticfiles:/home/azureuser/stratify/staticfiles
      - ./mediafiles:/home/azureuser/stratify/mediafiles
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    command: >
      /bin/sh -c "
        apt update -y &&
        apt install -y --no-install-recommends certbot python3-certbot-nginx &&
        rm -rf /var/lib/apt/lists/* &&
        echo holaa &&
        certbot --nginx -d stratify.eastus.cloudapp.azure.com --email ${EMAIL_HOST_USER} --agree-tos --no-eff-email &&
        echo holaa &&
        sleep 15 &&
        nginx -g 'daemon off;'
      "
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  backend:
  frontend: